-- Supabase SQL Schema for Shop-Flow Application
-- Run this in your Supabase SQL Editor to create all necessary tables

-- Enable RLS (Row Level Security)
alter schema public enable row level security;

-- 1. Contact Form Submissions
create table contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz default now() not null
);

-- 2. Authentication Verification Codes
create table auth_verifications (
  email text primary key,
  code text not null,
  expires_at timestamptz not null,
  created_at timestamptz default now() not null
);

-- 3. Checkout Sessions
create table checkout_sessions (
  id bigint generated by default as identity primary key,
  email text not null,
  cart jsonb not null,
  payment_gateway text not null,
  total_amount text not null,
  currency text not null,
  status text not null default 'pending', -- pending, paid, failed, expired
  sellauth_invoice_id text,
  sellauth_checkout_url text,
  paypal_payment_id text,
  paypal_approval_url text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 4. Order History (from SellAuth)
create table orders (
  id bigint generated by default as identity primary key,
  sellauth_invoice_id text not null unique,
  customer_email text not null,
  customer_id bigint,
  cart jsonb not null,
  total_amount text not null,
  currency text not null,
  status text not null,
  payment_gateway text not null,
  paid_at timestamptz,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 5. Customer Sessions (for tracking active sessions)
create table customer_sessions (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  customer_id bigint not null,
  customer_email text not null,
  ip_address text,
  user_agent text,
  expires_at timestamptz not null,
  created_at timestamptz default now() not null
);

-- 6. Payment Methods Configuration
create table payment_methods (
  id bigint generated by default as identity primary key,
  gateway text not null unique,
  is_active boolean default true,
  config jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Insert default payment methods
insert into payment_methods (gateway, config) values
('STRIPE', '{"enabled": true}'),
('PAYPAL', '{"enabled": true, "email": "kaerlin.offical@gmail.com"}'),
('BTC', '{"enabled": false}'),
('LTC', '{"enabled": false}');

-- 7. Products Cache (optional, for performance)
create table product_cache (
  id bigint primary key,
  name text not null,
  path text not null,
  price text not null,
  currency text not null,
  description text,
  image_url text,
  stock_count integer,
  group_id bigint,
  group_name text,
  variants jsonb,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- Row Level Security Policies

-- Contacts: Anyone can insert, but only authenticated users can read
create policy "Anyone can insert contacts" on contacts for insert with check (true);
create policy "Authenticated users can read contacts" on contacts for select using (auth.role() = 'authenticated');

-- Auth verifications: Anyone can insert/update their own email
create policy "Anyone can manage their auth verification" on auth_verifications for all using (email = current_setting('app.current_email', true));

-- Checkout sessions: Users can only see their own sessions
create policy "Users can see own checkout sessions" on checkout_sessions for select using (email = current_setting('app.current_email', true));
create policy "Users can insert own checkout sessions" on checkout_sessions for insert with check (email = current_setting('app.current_email', true));

-- Orders: Users can only see their own orders
create policy "Users can see own orders" on orders for select using (customer_email = current_setting('app.current_email', true));
create policy "Service can insert orders" on orders for insert with check (auth.role() = 'service_role');

-- Customer sessions: Service role only
create policy "Service role full access to sessions" on customer_sessions for all using (auth.role() = 'service_role');

-- Payment methods: Read-only for everyone, service role can manage
create policy "Anyone can read payment methods" on payment_methods for select using (true);
create policy "Service role can manage payment methods" on payment_methods for all using (auth.role() = 'service_role');

-- Product cache: Read-only for everyone, service role can manage
create policy "Anyone can read product cache" on product_cache for select using (true);
create policy "Service role can manage product cache" on product_cache for all using (auth.role() = 'service_role');

-- Indexes for performance
create index idx_contacts_email on contacts(email);
create index idx_auth_verifications_expires on auth_verifications(expires_at);
create index idx_checkout_sessions_email on checkout_sessions(email);
create index idx_checkout_sessions_status on checkout_sessions(status);
create index idx_orders_customer_email on orders(customer_email);
create index idx_orders_status on orders(status);
create index idx_orders_sellauth_id on orders(sellauth_invoice_id);
create index idx_customer_sessions_expires on customer_sessions(expires_at);
create index idx_product_cache_updated on product_cache(updated_at);

-- Function to automatically update updated_at timestamp
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

-- Triggers for updated_at
create trigger update_checkout_sessions_updated_at before update on checkout_sessions for each row execute function update_updated_at_column();
create trigger update_orders_updated_at before update on orders for each row execute function update_updated_at_column();
create trigger update_payment_methods_updated_at before update on payment_methods for each row execute function update_updated_at_column();
create trigger update_product_cache_updated_at before update on product_cache for each row execute function update_updated_at_column();

-- Function to clean up expired verifications
create or replace function cleanup_expired_verifications()
returns void as $$
begin
  delete from auth_verifications where expires_at < now();
end;
$$ language plpgsql;

-- Function to clean up expired sessions
create or replace function cleanup_expired_sessions()
returns void as $$
begin
  delete from customer_sessions where expires_at < now();
end;
$$ language plpgsql;

-- Clean up expired data daily (you can set this up in Supabase Dashboard > Database > Triggers)
-- This would need to be scheduled via pg_cron or Supabase Edge Functions
